### ISSUE TITLE
Consider excluding 2015

### ISSUE THREAD

**Issue by JCHS-Riordan** [JCHS-Riordan/IRS-county-level-migration#6]
I forgot about this issue (or forgot about how much of a problem it was), but there are intense data irregularities in the 2015 migration data. My contact at the IRS says it was because of efforts to fight identity theft that year that had the unintended consequence of screwing up the data. From what I can tell, the effect is magnifying all the patterns: steeper negative net flows and steeper positive net flows.

I excluded 2015 in the blog, and also 2013 for the sake of symmetry in the charts. Since we don't have those types of charts here, just excluding 2015 should be sufficient. Even if we make charts over time, they won't be just 2012-2016 like in the blog, so excluding 2015 will look odd but not create as big of a symmetry issue.

**Comment by JCHS-Riordan** [comment]
An example of the effects of 2015 data quality:  ![image](https://user-images.githubusercontent.com/37803786/38147712-702d3674-3421-11e8-8b62-05abc84c49ca.png)

**Comment by JCHS-Matthew** [comment]
We could just exclude 2015 with a note, or do only even years, or do something like 1995, 2000, 2005, 2008, 2010, 2012, 2014, 2016?

For testing we can just filter out the years in the javascript, but eventually we want to exclude years from the source data sheet.

**Comment by JCHS-Riordan** [comment]
I commented out SheetID_2015 in the JS and the 2015 option in the year drop-down menu in the HTML, and updated the notes to include mention of the 2015 exclusion. With this particular set-up, that's basically the same as deleting the source data, since each year has it's own sheet (except Net Flows, but 2015 Net Flows simply can't be accessed due to the drop-down menu). Will have to be a different solution for the state map, but this works here, since symmetry is not as much of a problem with the drop-down menu.
